### ISSUE TITLE
The plugins skips the night even when just one person sleeps

### ISSUE THREAD

**Issue by deadman96385** [CommanderTvis/bukkit-morpheus#2] opened 2018-10-19 20:35 UTC
**Description**
We have 6 players on and no matter who sleeps it always skips the night

**Expected behavior**
Should wait till 50% 

**Environment:**
 - Minecraft server version: 
1.13.1
 - Minecraft client version: 
1.13.1
 - Java version: 
Java 8
 - Plugin version: 
0.1
 - Bukkit/Spigot version: 
git-spigot-f6a273b-cd6252a (1.13.1-R0.1-SNAPSHOT)
 - OS: 
CentOS 7

**Comment by MDMCK10** [comment] 2018-10-19 20:38
this is most likely a duplicate of #1

**Comment by deadman96385** [comment] 2018-10-19 20:39
Probably similar but we don't need to to it multiple times for it to trigger it always does it

**Comment by MDMCK10** [comment] 2018-10-19 20:39
but, there is something else relevant to this that i found: by default in the config, the "percentage" is set to 0.5, but for it to be actually 50%, i had to set that to 50, which means the default is 0.5%?

**Comment by CommanderTvis** [comment] 2018-10-19 20:40
0.5 in the config should mean 50%

**Comment by MDMCK10** [comment] 2018-10-19 20:45
i stand corrected, when set to 1, it appears to be 1%, because even though there are 2 players on the server, it will still skip day if only 1 player sleeps

**Comment by MDMCK10** [comment] 2018-10-19 20:46
however, when set to 100, it requires both players to sleep

**Comment by MDMCK10** [comment] 2018-10-19 20:47
another thing i noticed, is if there are only 2 players online and it's set to 100%, if you sleep for long enough, it will be day anyway

**Closed** 2018-10-20 07:51 UTC
Labels: duplicate
